node:
  endpoint:
    ethereum: "https://tn.henesis.io/ethereum/goerli?clientId=815fcd01324b8f75818a755a72557750"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect