node:
  endpoint:
    ethereum: "https://tn.henesis.io/ethereum/goerli?clientId=815fcd01324b8f75818a755a72557750"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
      format_sql: true
      show_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

